# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7dcf15c0280f4f96ac3e3b6b07f4d89b"
name = "QC-POS"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[pos]
embedded = true
