api_version = "2025-10"

[[extensions]]
type = "ui_extension"
name = "QC Card & Pin"
uid = "d08c2a49-f4ac-6173-2819-000c4e4278d38e08333d"
handle = "qwikcliver-wallet"
description = "QC Card & Pin"

# module: file that contains your extension’s source code
# target: location where your extension appears in POS
[[extensions.targeting]]
module = "./src/Tile.jsx"
target = "pos.home.tile.render"

[[extensions.targeting]]
module = "./src/Modal.jsx"
target = "pos.home.modal.render"
