api_version = "2025-10"

[[extensions]]
type = "ui_extension"
name = "Enter Gift card details"
uid = "7b7cd599-89af-5f08-33ff-51f87ed81c9da7c1a8ba"
handle = "gift-card-options-physical"
description = "Enter Gift card details"

# module: path to the file that contains your extension’s source code
# target: string that describes where your extension appears in POS
[[extensions.targeting]]
module = "./src/Action.jsx"
target = "pos.cart.line-item-details.action.render"

# You can omit the menu-item target and POS will provide a default menu item for this extension.
# The menu item will present the action target on click.
# This template has the same behavior as the POS-provided default, but is included for completeness.
[[extensions.targeting]]
module = "./src/MenuItem.jsx"
target = "pos.cart.line-item-details.action.menu-item.render"
