api_version = "2025-10"

[[extensions]]
type = "ui_extension"
name = "Barcode Scan"
uid = "ca1e9e3e-e51b-cfaf-606d-ec2e754a0986b8a0ed10"
handle = "barcode-scan"
description = "Barcode Scan"

# module: file that contains your extension’s source code
# target: location where your extension appears in POS
[[extensions.targeting]]
module = "./src/Tile.jsx"
target = "pos.home.tile.render"

[[extensions.targeting]]
module = "./src/Modal.jsx"
target = "pos.home.modal.render"
