api_version = "2025-10"

[[extensions]]
type = "ui_extension"
name = "QC Add Balance - Wallet"
uid = "30202201-d5e1-32ab-f413-c5cc16a798eee890c0ae"
handle = "qc-add-balance"
description = "QC Add Balance - Wallet"

# module: file that contains your extension’s source code
# target: location where your extension appears in POS
[[extensions.targeting]]
module = "./src/Tile.jsx"
target = "pos.home.tile.render"

[[extensions.targeting]]
module = "./src/Modal.jsx"
target = "pos.home.modal.render"
